- name: install apache
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - apache2
    - libapache2-mod-php7.0


- name: "apache vhost config"
  template: src=000-default.conf.j2 dest=/etc/apache2/sites-enabled/000-default.conf mode=0644
  notify:
    - restart apache